version: '3'
services:
        web:
                image: tripleaj_port_v2
                build: .
                ports:
                        - "8081:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
